---
name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-super-linter:
    uses bretfisher/super-linter-example/.github/workflows/super-linter.yaml@main
